### ISSUE TITLE
Top panel issues when using Elementary OS

### ISSUE THREAD

**Issue by skewty** [paullinuxthemer/Nextwaita#1]
I added this to to the bottom of `gtk.css` to improve things.

```css
/***************************************
 * Panel adjustments for Elementary OS *
 ***************************************/

.panel {
    margin-right: 10px;
    background-color: rgba(0, 0, 0, 0.6);
    transition: all 100ms ease-in-out;
}
.panel image {
    margin-right: 8px;
}
.panel.maximized label {
    color: white;
}
.panel.maximized {
    color: white; /* affects the search icon */
    background-color: #404040;
    border-bottom: 1px solid black;
}
menubar.panel, .panel menubar {
    /* removes the lingering underline from labels in the top panel */
    box-shadow: none;
    border: none;
}

```

# See the before and after below:

## Before
![screenshot from 2019-02-17 09-26-09](https://user-images.githubusercontent.com/9087223/52916679-6ce66600-3297-11e9-9c3b-472eaa477585.png)
![screenshot from 2019-02-17 09-26-13](https://user-images.githubusercontent.com/9087223/52916680-6ce66600-3297-11e9-8328-7c9d0e783829.png)

## After
![screenshot from 2019-02-17 09-23-50](https://user-images.githubusercontent.com/9087223/52916681-6ce66600-3297-11e9-91e0-fd382bb7b386.png)
![screenshot from 2019-02-17 09-23-57](https://user-images.githubusercontent.com/9087223/52916678-6ce66600-3297-11e9-8ff3-d2ea49f55112.png)

I personally prefer a little more font weight in the panel when maximized so I use this:

```css
/***************************************
 * Panel adjustments for Elementary OS *
 ***************************************/

.panel {
    margin-right: 10px;
    background-color: rgba(0, 0, 0, 0.6);
    transition: all 100ms ease-in-out;
}
.panel image {
    /* affects the search icon */
    margin-right: 8px;
}
.panel.maximized label, .panel.maximized image {
    color: white;
}
.panel.maximized {
    background-color: #404040;
    border-bottom: 1px solid black;
    font-weight: bolder;
}
menubar.panel, .panel menubar {
    /* removes the lingering underline from labels in the top panel */
    box-shadow: none;
    border: none;
}
```
